### ISSUE TITLE
puppetdb_json.py not working against Puppet Enterprise

### ISSUE THREAD

**Issue by bzilla** [maxadamo/patching_status#2]
I'm trying to get puppetdb_json.py to work with Puppet Enterprise 2019.1.1, which I understand uses certificates for the connection, but so far no luck.  My python is rusty but I'm trying to work through it.  The output that the current version of this script, when pointed at my puppetdb, is:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./puppetdb_json.py", line 40, in <module>
    PUPPETDB, PUPPETDB_PORT), PARAMS)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine('\x15\x03\x03\x00\x02\x02P',))
```
I'm running this on RHEL 7.7.

**Comment by maxadamo** [comment]
hi @bzilla 
I did not consider that puppetDB can have SSL enabled. 
Since I don't have puppetDB with SSL enabled, I'll need your help to fix and troubleshoot this issue. 
What do you need to do to get the following command working against your puppetdb? (you can mask your hostname, domainname...): 
```
curl -s -X POST http://puppetdb02.mydomain.org:8080/pdb/query/v4/facts -H 'Content-Type:application/json' -d '{"query": ["and",["=", "name", "os"]], "pretty": "true", "limit": 2}'
```

**Comment by maxadamo** [comment]
otherwise, PRs are welcome :tada: :eyes: :smile_cat:

**Comment by bzilla** [comment]
I'd love to get a PR in, I'll just need to hack on the python a fair bit. :)

The curl command I have working uses an https URL (using the FQDN) and the curl certificate flags:

```
curl -s -X POST https://<puppetdb_fqdn>:8081/pdb/query/v4/facts \
     --cacert /etc/puppetlabs/puppet/ssl/certs/ca.pem \
     --cert /etc/puppetlabs/puppet/ssl/certs/<certname>.pem \
     --key /etc/puppetlabs/puppet/ssl/private_keys/<certname>.pem \
     -H 'Content-Type:application/json' \
     -d '{"query": ["and",["=", "name", "os"]], "pretty": "true", "limit": 2}'
```
My thoughts on how I would update the module would be to pass in the cert options as hiera, and modify it to use a URL rather than an IP for the puppetdb parameter.  Open to ideas of course but I'll work towards that as I have some time this week.

Side note, thank you very much for starting this module! I'm hoping to get a lot of value out of it, and provide more input as I go.

**Comment by maxadamo** [comment]
now I see it and I recall that this is the same when I query the puppet server API. It means that I can test it, by running some fake query against the puppet server. I didn't want to ask you to test every couple of hours.

**Comment by maxadamo** [comment]
@bzilla now you can test it, but it's not on forge. You need to use the module from Github, master branch. 
I would be surprised if it work without any test from my side... if it doesn't work, I try to figure out a way to test it. 

You can use hiera to store the content of the certificate (please note: for the key you need to specify `Sensitive`... if you use `eyaml` it's even better). 
You can have a look here: [patching_status#enabling-ssl](https://github.com/maxadamo/patching_status#enabling-ssl)

**Comment by bzilla** [comment]
This update does indeed work, but rather than placing certs in hiera, I think for a Puppet Enterprise use case, we would prefer to specify file-system paths rather than supply cert content.  In PE, this connection to puppetdb is made using the client cert on the system initiating the call rather than the server cert of the puppetdb, and references the CA that the entire Puppet cert ecosystem uses which we also keep local.

See my curl command above for path examples.  Or maybe the option to do either if there's a use case for using cert content that I'm unfamiliar with.

I could setup a PR with this change to just use paths unless you want to keep the direction of the cert content as it is.

**Comment by maxadamo** [comment]
yes, feel free to amend it. 
Right now I am placing certificate, key and CA, under `${script_base}/puppetdb_certs/`, by using the content that you can store in hiera. 
We also need to consider that the key is sensitive.

**Comment by maxadamo** [comment]
@bzilla meanwhile I uploaded the new version on puppet forge. We'll think how/if we can improve the way we handle the certificate.

**Comment by bzilla** [comment]
Hi @maxadamo , may I please get write access to push a branch up for a PR?

**Comment by maxadamo** [comment]
I have added you. I have also created a branch, but feel free to create other branches

**Comment by maxadamo** [comment]
resolved by https://github.com/maxadamo/patching_status/pull/3
